((python-mode . ((indent-tabs-mode . nil)))
 (autoconf-mode . ((indent-tabs-mode . t)))
 (c++-mode . ((c-file-style . "linux")
              (indent-tabs-mode . t)
              (tab-width . 8)
              (c-basic-offset . 8)
              (c-file-offsets .
                          ((arglist-close . 0)
                           (arglist-cont-nonempty . +)
                           (arglist-intro . +)
                           (brace-list-entry . 0)
                           (brace-list-intro . +)
                           (brace-list-close . 0)
                           (case-label . 0)
                           (statement-cont . +)
                           (substatement-open . 0)
                           (block-open . 0)
                           (knr-argdecl-intro . +)
                           (inline-open . 0)
                           (label . 0)))))
 (c-mode . ((c-file-style . "linux")
            (indent-tabs-mode . t)
            (tab-width . 8)
            (c-basic-offset . 8)
            (c-file-offsets .
                          ((arglist-close . 0)
                           (arglist-cont-nonempty . +)
                           (arglist-intro . +)
                           (brace-list-entry . 0)
                           (brace-list-intro . +)
                           (brace-list-close . 0)
                           (case-label . 0)
                           (statement-cont . +)
                           (substatement-open . 0)
                           (block-open . 0)
                           (knr-argdecl-intro . +)
                           (inline-open . 0)
                           (label . 0))))))
