#! /bin/sh

echo "NOTE: this script is obsolete.  Use autoreconf instead!"
echo Running libtoolize...
libtoolize --automake
echo Running aclocal...
aclocal
echo Running autoheader...
autoheader
echo Running autoconf...
autoconf
echo Running automake...
automake -a -c
rm -f config.cache config.status
echo "To compile run './configure', and then 'make'."
