.TH FUSERMOUNT3 1 2011\-10\-23 2.8.6 "Filesystem in Userspace (FUSE)"

.SH NAME
\fBfusermount3\fR \- mount and unmount FUSE filesystems

.SH SYNOPSIS
\fBfusermount3\fR [\fIOPTIONS\fR] \fIMOUNTPOINT\fR

.SH DESCRIPTION
Filesystem in Userspace (FUSE) is a simple interface for userspace programs to export a virtual filesystem to the Linux kernel. It also aims to provide a secure method for non privileged users to create and mount their own filesystem implementations.
.PP
\fBfusermount3\fR is a program to mount and unmount FUSE
filesystems. It should be called directly only for unmounting FUSE
file systems. To allow mounting and unmounting by unprivileged users,
\fBfusermount3\fR needs to be installed set-uid root.
.SH OPTIONS
.IP "\-h" 4
print help.
.IP "\-V" 4
print version.
.IP "-o \fIOPTION\fR[,\fIOPTION\fR...]" 4
mount options.
.IP "-u" 4
unmount.
.IP "-q" 4
quiet.
.IP "-z" 4
lazy unmount.

.SH SEE ALSO
\fImount\fR(8),
\fImount.fuse\fR(8),

.SH HOMEPAGE
More information about fusermount3 and the FUSE project can be found at <\fIhttp://fuse.sourceforge.net/\fR>.

.SH AUTHORS
.LP
FUSE is currently maintained by Nikolaus Rath <Nikolaus@rath.org>
.LP
The original author of FUSE is Miklos Szeredi <\fImiklos@szeredi.hu\fR>.
.LP
This manual page was originally written by Daniel Baumann <\fIdaniel.baumann@progress\-technologies.net\fR>.
