.TH FUSERMOUNT 1 2011\-10\-23 2.8.6 "Filesystem in Userspace (FUSE)"

.SH NAME
\fBfusermount\fR \- mount and unmount FUSE filesystems

.SH SYNOPSIS
\fBfusermount\fR [\fIOPTIONS\fR] \fIMOUNTPOINT\fR

.SH DESCRIPTION
Filesystem in Userspace (FUSE) is a simple interface for userspace programs to export a virtual filesystem to the Linux kernel. It also aims to provide a secure method for non privileged users to create and mount their own filesystem implementations.
.PP
\fBfusermount\fR is a program to mount and unmount FUSE filesystems.

.SH OPTIONS
.IP "\-h" 4
print help.
.IP "\-V" 4
print version.
.IP "-o \fIOPTION\fR[,\fIOPTION\fR...]" 4
mount options.
.IP "-u" 4
unmount.
.IP "-q" 4
quiet.
.IP "-z" 4
lazy unmount.

.SH SEE ALSO
\fImount\fR(8),
\fImount.fuse\fR(8),
\fIulockmgr_server\fR(1).

.SH HOMEPAGE
More information about fusermount and the FUSE project can be found at <\fIhttp://fuse.sourceforge.net/\fR>.

.SH AUTHOR
FUSE was written by Miklos Szeredi <\fImiklos@szeredi.hu\fR>.
.PP
This manual page was written by Daniel Baumann <\fIdaniel.baumann@progress\-technologies.net\fR>.
