---
name: 'libfuse ABI check'

on:
  push:
    branches:
      - master
      - 'fuse-[0-9]+.[0-9]+*'  # This will match branches like 3.17, 3.18, 4.0, etc.
  pull_request:
    branches:
      - master
      - 'fuse-[0-9]+.[0-9]+*'
permissions:
  contents: read

jobs:
  abi:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: current

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          ./current/.github/workflows/install-ubuntu-dependencies.sh --abicheck

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: previous
          ref: ${{ github.event.pull_request.base.ref }}

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install -r current/requirements.txt

      - name: Run ABI check
        run: |
          current/.github/workflows/abicheck.sh --current-dir current --previous-dir previous
