---
# TODO: integrate into matrix.os in pr-ci.yml
# TODO: add NetBSD and DragonFlyBSD
name: 'Build (FreeBSD)'
on:
  push:
    branches:
      - master
      - 'fuse-[0-9]+.[0-9]+*'
  pull_request:
    branches:
      - master
      - 'fuse-[0-9]+.[0-9]+*'

jobs:
  build_bsd:
    runs-on: ubuntu-latest
    name: Build under FreeBSD
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Build
      uses: vmactions/freebsd-vm@7ca82f79fe3078fecded6d3a2bff094995447bbd # v1
      with:
        usesh: true
        prepare: |
          pkg install -y meson ninja
        run: |
          mkdir build
          cd build
          meson setup ..
          ninja -v
...